[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day6 = "CeQJK4PX4hjZMrqj6NJyJCeDro61hUbGCA5AKKCfAk7q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
