[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day5 = "ALKKgt9LJuf7RzyNh2B6dVjwBh7eWC8DAu1T3dRvoic7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
